apiVersion: v1
entries:
  block-user-service:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-03-06T17:04:18.319357294Z"
    description: A Helm chart for the block-user-service
    digest: 5422ff78f3ad5dac578f971b9c00bbf33c6727ed7bdc509829f193b2134bb02d
    name: block-user-service
    type: application
    urls:
    - block-user-service-0.0.12.tgz
    version: 0.0.12
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-03-06T17:04:18.318577964Z"
    description: A Helm chart for the block-user-service
    digest: a9c72f2dbb362fc83da7188b8d52f9883d8a6140e2a6680a1fd0ba2a28c4a588
    name: block-user-service
    type: application
    urls:
    - block-user-service-0.0.10.tgz
    version: 0.0.10
generated: "2022-03-06T17:04:18.317886137Z"
